### ISSUE TITLE
Failed to install Micromamba

### ISSUE THREAD

**Issue by JavierYepez** [mamba-org/devcontainer-features#26]
Hi, I was trying to create a dev container with Micromamba but it's failing.

Here are the logs:
```
4.698 Micromamba configured.
4.698 Create env by /tmp/env.yml...
4.705 error    libmamba Overwriting root prefix is not permitted
4.705 critical libmamba Aborting.
4.706 ERROR: Feature "micromamba" (ghcr.io/mamba-org/devcontainer-features/micromamba) failed to install! Look at the documentation at https://github.com/mamba-org/devcontainer-features/tree/main/src/micromamba for help troubleshooting this error.
------
[2024-01-21T17:48:00.234Z] Dockerfile-with-features:27
--------------------
  26 |     ENV PATH="/opt/conda/bin:${PATH}"
  27 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=micromamba_0,target=/tmp/build-features-src/micromamba_0 \
  28 | >>>     cp -ar /tmp/build-features-src/micromamba_0 /tmp/dev-container-features \
  29 | >>>  && chmod -R 0755 /tmp/dev-container-features/micromamba_0 \
  30 | >>>  && cd /tmp/dev-container-features/micromamba_0 \
  31 | >>>  && chmod +x ./devcontainer-features-install.sh \
  32 | >>>  && ./devcontainer-features-install.sh \
  33 | >>>  && rm -rf /tmp/dev-container-features/micromamba_0
  34 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/micromamba_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/micromamba_0  && cd /tmp/dev-container-features/micromamba_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-featu
[2024-01-21T17:48:00.234Z] res/micromamba_0" did not complete successfully: exit code: 1

View build details: ]8;;docker-desktop://dashboard/build/desktop-linux/desktop-linux/jzhhn77pjoahsq57xg5429j0e\docker-desktop://dashboard/build/desktop-linux/desktop-linux/jzhhn77pjoahsq57xg5429j0e]8;;\
[2024-01-21T17:48:00.236Z] Stop (5997 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/f_/cp1hrwld6dxcbvlwg2klx009s9kr63/T/devcontainercli/container-features/0.54.1-1705859272479/Dockerfile-with-features -t vsc-rope-d4ef84f81103eee2ac708ed1c4c04cd1c2d7beca112c0a9d54caba7b72c9c8c4 --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/var/folders/f_/cp1hrwld6dxcbvlwg2klx009s9kr63/T/devcontainercli/container-features/0.54.1-1705859272479 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /Users/jyepez/Documents/Projects/rope/.devcontainer
[2024-01-21T17:48:00.237Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/f_/cp1hrwld6dxcbvlwg2klx009s9kr63/T/devcontainercli/container-features/0.54.1-1705859272479/Dockerfile-with-features -t vsc-rope-d4ef84f81103eee2ac708ed1c4c04cd1c2d7beca112c0a9d54caba7b72c9c8c4 --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/var/folders/f_/cp1hrwld6dxcbvlwg2klx009s9kr63/T/devcontainercli/container-features/0.54.1-1705859272479 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /Users/jyepez/Documents/Projects/rope/.devcontainer
[2024-01-21T17:48:00.237Z]     at Y$ (/Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:463:1860)
[2024-01-21T17:48:00.237Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-01-21T17:48:00.237Z]     at async Fw (/Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:1831)
[2024-01-21T17:48:00.237Z]     at async $J (/Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:608)
[2024-01-21T17:48:00.237Z]     at async tAA (/Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2024-01-21T17:48:00.237Z]     at async CC (/Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2024-01-21T17:48:00.237Z]     at async NeA (/Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[2024-01-21T17:48:00.237Z]     at async MeA (/Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[2024-01-21T17:48:00.239Z] Stop (8220 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jyepez/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-5e6d2a45-5bbb-4c54-abb7-fb10e37d46891705859271126 --workspace-folder /Users/jyepez/Documents/Projects/rope --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jyepez/Documents/Projects/rope --id-label devcontainer.config_file=/Users/jyepez/Documents/Projects/rope/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/jyepez/Documents/Projects/rope/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-21T17:48:00.239Z] Exit code 1
[2024-01-21T17:48:00.241Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/jyepez/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jyepez/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-5e6d2a45-5bbb-4c54-abb7-fb10e37d46891705859271126 --workspace-folder /Users/jyepez/Documents/Projects/rope --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jyepez/Documents/Projects/rope --id-label devcontainer.config_file=/Users/jyepez/Documents/Projects/rope/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/jyepez/Documents/Projects/rope/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-21T17:48:00.241Z] Exit code 1
```

Here the devcontainer.json:

```
{
	"name": "Debian",
	"build": { "dockerfile": "Dockerfile" },
	"features": {
		"ghcr.io/mamba-org/devcontainer-features/micromamba:1": {
			"envFile": "/tmp/env.yml"
		}
	},
	"customizations": {
		"vscode": {
			"extensions": [
				"ms-python.python"
			]
		}
	}
}
```

And the Dockerfile:

```
FROM mcr.microsoft.com/devcontainers/base:bullseye
COPY env.yml /tmp/env.yml
```

**Comment by eitsupi** [comment]
Hmmm... does not seem reproduced on CI.
https://github.com/mamba-org/devcontainer-features/actions/runs/7611656103/job/20727566825?pr=27#step:4:2215

Could you share the env file?

**Comment by maresb** [comment]
I can reproduce it. I think it's because micromamba create doesn't work with base. We should switch to micromamba install, but this may involve some logic.

**Comment by JavierYepez** [comment]
The env file:
```
name: base
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python==3.11
  - pytorch
  - opencv
  - matplotlib
  - ipykernel
  - pip
```
